baseURL = "/"
languageCode = "pt-BR"
title = "Luiza Lian"
theme = "lulian"

pluralizelisttitles =false
enableEmoji = true
enableGitInfo = true
enableRobotsTXT=true
googleAnalytis  = ""
disqusShortname = ""
SectionPagesMenu="main"
footnoteReturnLinkContents = "↩"
pygmentsCodeFences = true

[params]
  selo = "https://www.facebook.com/selorisco"
  [params.social]
    facebook		= "luizalian"
    instagram		= "luizalian"
    youtube		  = "user/luizalianshow"
    soundcloud  = "luizalian"
    spotify     = "artist/0mqrSBamArf14pPZE2Q9kW"
  
  [params.analytics]
    uid = "UA-960953172"

[imaging]  
  quality = 85

[menu]
  [[menu.main]]
    identifier = "albums"
    name = "This is the blog section"
    title = "albums"
    url = "/albums/"
    weight = 100
  [[menu.main]]
    identifier = "contact"
    name = "This is the contact section"
    title = "contact"
    url = "/contact/"
    weight = 200    